resolver: lts-19.4
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages
extra-deps:
- package-version-0.1.0.0@sha256:bb9fc93e905540aa8e1b32f80c2dc82756a4481c63779bd92e3796ed8085ab98,2854
- strict-io-0.2.2@sha256:1cc96f9a123a919ff9ee479f740cbc9fa9edf7c8ac65334de3fdce07638949ed,1012
- git: https://github.com/tbidne/algebra-simple.git
  commit: be105b31e3bd2bc00c69cd5c1e869294b26fbb17
- git: https://github.com/tbidne/env-guard.git
  commit: 89a68d033d0671239b5e5e4a31f4355c46d4b6d3
- git: https://github.com/tbidne/relative-time.git
  commit: dd4bf2a37bc22763eed6c9bf80ada9b323fb7a22
flags:
  refined:
    aeson: false
    quickcheck: false
nix:
  shell-file: nix/stack.nix