name: cabal

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/ad47284f8b01f587e24a4f14e0f93126d8ebecda.tar.gz:nixos-config=configuration.nix

      - name: Compile
        run: nix-shell shell.nix --command "cabal update && cabal v2-build"

      - name: Unit Test
        run: nix-shell shell.nix --command "cabal update && cabal v2-test unit --test-show-details=direct"

      - name: Functional Test
        run: nix-shell shell.nix --command "cabal update && cabal v2-test functional --test-show-details=direct"
