name: cabal

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  cabal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/f02bf8ffb9a5ec5e8f6f66f1e5544fd2aa1a0693.tar.gz:nixos-config=configuration.nix

      - name: Compile
        run: nix-shell shell.nix --command "cabal update && cabal v2-build"

      # Commented out for now because ~~life is cruel~~ cabal+doctest
      # inexplicably started failing on CI for no discernable reason.
      # The error message is:
      #
      #   src/ShellRun/Logging/Log.hs:33:1: error:
      #   Could not find module ‘System.Console.Pretty’
      #
      # Which would be great, except:
      #   1. Why does it need to find this module? I haven't told
      #      doctest about any of my other deps, and doctest does
      #      not actually compile the project.
      #   2. Doctest shouldn't even be looking at the Log module anyway,
      #      since it's not used in any of the listed files in Main.hs.
      #   3. Nothing relevant (from what I can tell) changed between failures!
      #- name: Doc Test
      #  run: nix-shell shell.nix --command "cabal update && cabal v2-test doctest --write-ghc-environment-files=always --test-show-details=direct"

      - name: Unit Test
        run: nix-shell shell.nix --command "cabal update && cabal v2-test unit --test-show-details=direct"
      
      - name: Integration Test
        run: nix-shell shell.nix --command "cabal update && cabal v2-test integration --test-show-details=direct"

      - name: Functional Test
        run: nix-shell shell.nix --command "cabal update && cabal v2-test functional --test-show-details=direct"
