name: cabal

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  cabal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/f02bf8ffb9a5ec5e8f6f66f1e5544fd2aa1a0693.tar.gz:nixos-config=configuration.nix

      - name: Compile
        run: nix-shell shell.nix --command "cabal update && cabal v2-build"

      - name: Doc Test
        run: nix-shell shell.nix --command "cabal update && cabal v2-test doctest --test-show-details=direct"

      - name: Unit Test
        run: nix-shell shell.nix --command "cabal update && cabal v2-test unit --test-show-details=direct"
      
      - name: Integration Test
        run: nix-shell shell.nix --command "cabal update && cabal v2-test integration --test-show-details=direct"

      - name: Functional Test
        run: nix-shell shell.nix --command "cabal update && cabal v2-test functional --test-show-details=direct"
