name: "9.0.2"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal_9-0-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b2737d4980a17cc2b7d600d7d0b32fd7333aca88.tar.gz

      - name: Compile
        run: |
          nix-shell nix/ghc_9-0-2.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always"

      - name: DocTest
        run: |
          nix-shell nix/ghc_9-0-2.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always && \
             RUN_DOCTEST=true cabal test doctest --test-show-details=direct"

      - name: Unit Tests
        run: |
          nix-shell nix/ghc_9-0-2.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always && \
             cabal test unit --test-show-details=direct"

      - name: Integration Tests
        run: |
          nix-shell nix/ghc_9-0-2.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always && \
             cabal test integration --test-show-details=direct"

      - name: Functional Tests
        run: |
          nix-shell nix/ghc_9-0-2.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always && \
             cabal test functional --test-show-details=direct"