name: hlint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/ad47284f8b01f587e24a4f14e0f93126d8ebecda.tar.gz:nixos-config=configuration.nix

      - name: Check hlint
        run: nix-shell shell.nix --command "bash ./ci_scripts/hlint.sh"
