name: nix

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      
      - name: Compile & Test
        run: |
          nix build
          if [ -f "./result/bin/shell-run" ]; then
            echo "Build succeeded"
          else
            echo "Build failed"
            exit -1
          fi
